version: "3"
services:
  backend:
    build:
      context: backend
    environment:
      DB_TABLENAME: Idea-centered-inquiry #<DB_TABLENAME>
      DB_USERNAME: wulab #<USERNAME>
      DB_USERPSW: ytwu35415 #<USERPSW>
      DB_HOST: db
    restart: always
    ports:
        - "8000:8000"
    depends_on:
        - db

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: Idea-centered-inquiry #<DB_TABLENAME> 
      POSTGRES_USER: wulab #<USERNAME> 
      POSTGRES_PASSWORD: ytwu35415 #<USERPSW> 
      PGDATA: /var/lib/postgresql/data

    volumes:
      - "./db_data:/var/lib/postgresql/data"
    ports:
        - "5432:5432"

  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: "always"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: <PG_EMAIL>
  #     PGADMIN_DEFAULT_PASSWORD: <PG_PASSWORD>
  #     PGADMIN_LISTEN_PORT: 80
  #     PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
  #     PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
  #   ports:
  #       - "8080:80"
  #   volumes:
  #       - "./pgadmin_data:/var/lib/pgadmin"
  #   links:
  #       - "db:pgsql-server"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  frontend:
    build: 
      context: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    restart: always
    # volumes:
    #   - "./frontend:/app"
    depends_on:
      - backend

volumes:
    db_data:
    pgadmin_data:

networks:
  frontend:
  backend: